### ISSUE TITLE
NordWarUA's Vanilla Armor and Weapon Expansion - Complete Version installed without prerequisites

### ISSUE THREAD

**Issue by RyozuK** [iAmMe27/Tahrovin#1]
NordWarUA's Vanilla Armor and Weapon Expansion - Complete Version is an ESP only mod that adds armor entries.  These entries refer to meshes only available in original armor replacer found at https://www.nexusmods.com/skyrimspecialedition/mods/31679
This results in invisible enemies.

The enemies I found were at the tower on the way to Bleakfalls Barrow, though the armor can be seeded on any bandit I think.

**Comment by iAmMe27** [comment]
Many thanks for raising this, I shall look into before recompiling after LL come's back online fully.

**Comment by RyozuK** [comment]
No problem, and superb work on the modlist!

**Comment by iAmMe27** [comment]
Have fixed this and patched the armours in. Males should be wearing them whilst females should be wearing their skimpier replacements.
