### ISSUE TITLE
Tahrovin Quality DynDOLOD "403"

### ISSUE THREAD

**Issue by blackletum** [iAmMe27/Tahrovin#10]
From the log:

1799.64 - Unable to download Tahrovin Quality DynDOLOD Output.zip (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Tahrovin Quality DynDOLOD Output.zip_801fd1bb-83de-4aef-84ee-ffe5b91805d5)

So I attempted to go to the site directly, only to be met with a Forbidden 403 error.

I also attempted from the site:
https://build.wabbajack.org/authored_files
but with no luck.

**Comment by iAmMe27** [comment]
Please join the Discord for support, GitHub issues are for bugs with the modlist and not installation issues.
