### ISSUE TITLE
Google Drive files need to be updated! ! !

### ISSUE THREAD

**Issue by jimi202008** [iAmMe27/Tahrovin#11]
605.94 - Unable to download Tahrovin Performance DynDOLOD Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Tahrovin Performance DynDOLOD Output.7z_20eb5a17-6eed-4061-a3b4-096e0f17942f)
605.94 - Unable to download Tahrovin Quality DynDOLOD Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Tahrovin Quality DynDOLOD Output.7z_62ec9b59-4ce0-4455-88e5-e767feb02934)
605.94 - Unable to download Tahrovin Grass Stuff.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Tahrovin Grass Stuff.7z_a390cdf2-a7ec-4524-9812-3e71d0a87887)
605.94 - Unable to download Tahrovin xLODGen Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Tahrovin xLODGen Output.7z_d48b41cf-10a9-4b77-821d-890a29735a5a)
605.94 - Cannot continue, was unable to download one or more archives
605.95 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives

I can't get these files! ! !

**Comment by iAmMe27** [comment]
Activate "Network Workaround" in Wabbajack settings and then try again. If that doesn't work, use a free VPN with a US endpoint such as Proton VPN.

**Comment by iAmMe27** [comment]
Wiki page has been updated with new like to a Mega folder that contains the latest files.
