### ISSUE TITLE
INI Config Tool Doesn't open

### ISSUE THREAD

**Issue by DopieHD** [iAmMe27/Tahrovin#13]
After hitting the run button on the INI config tool it opens then closes immediately after.

**Comment by iAmMe27** [comment]
I also cannot get the tool to work for some reason. It has recently stopped working for me for no good reason and nothing I do seems to get it working. It is probably best to edit the INI files manually in MO2, which you can access from inside of MO2:

![image](https://user-images.githubusercontent.com/98499526/180186785-11e28bd6-a29a-43a3-b539-52c9d2fcd3f1.png)

**Comment by DopieHD** [comment]
thank you for responding!
