### ISSUE TITLE
Can't complete character creation. V0.9

### ISSUE THREAD

**Issue by TremerePuck** [iAmMe27/Tahrovin#16]
**Describe the bug**
Upon first launch and starting a new game the first quest popup text stays in view perpetually but half written. Character creation UI partially freezes after selecting "done" and hearing the sound of paper. No way to proceed. Unable to bring up game menu.

**To Reproduce**
1. Fresh install of Skyrim VR and Tahrovin using Steam and Wabbajack.
2. Launch game.
3. Select new game.
4. Click "Done" on creating character.

**Expected behavior**
Character creation should finish after clicking "Done".

**Hardware Specs**
Windows 10 21H2
Ryzen 5950X
RTX 2080ti
32GB DDR4
500GB SSD

**Comment by iAmMe27** [comment]
I ran through character creation from a new game less than an hour ago. So, a couple of tips:

1. Make sure you aren't using a massively aggressive antivirus (webroot, Bitdefender etc etc)
2. Make sure you added the Tahrovin folder to antivirus exceptions list
3. Make sure you increased your pagefile as per the readme
4. Make sure you increased your shader cache size as per the readme

If you're sure that you meet those 4 steps, it might be something is borked with the installation and I recommend deleting the `mods` folder that resides in your Tahrovin installation and then reinstalling from Wabbajack. It shouldn't take long if you didn't delete the downloads folder.

**Comment by TremerePuck** [comment]
I deleted the mods folder and reinstalled. Appears to work correctly now! Thank you.

**Comment by iAmMe27** [comment]
Glad to hear its all working now!
