### ISSUE TITLE
Disable Embers due to Perfomance

### ISSUE THREAD

**Issue by Flowrif** [iAmMe27/Tahrovin#18]
**Describe the bug**
I usually disable "Embers" mod due to performance issues. However, with the new update when I disable this mod, Skyrim VR will CTD after loading "Lux Merged" plugin. This only happens when I disable "Embers". After enabling again, Skyrim works fine. Is there any way I can exclude "Embers" without breaking the game?

**To Reproduce**
1. Open Game
2. Skyrim VR loads to menu for 2 seconds, then CTD
3. I checked crash logs and game crashes after loading "Lux Merged" plugin, only when "Embers" mod is disabled
4. I assume Lux is merged with Embers in this setup and relies on it somehow. Is there a way to bypass this?

**Expected behavior**
I would love if I can play Skyrim without "Embers" mod enable because it cost my PC performance.

**Screenshots**

**Additional context**

**Comment by iAmMe27** [comment]
This isn't a bug with Tahrovin, it's a modification and as such, not officially supported. Your best bet is to join the Discord server and ask in the #tahrovin-additions channel.
