### ISSUE TITLE
The instal fails. Path profile not found. I had it downloaded and working fine, and i got a new system and its done this 10 times.

### ISSUE THREAD

**Issue by BoobyMurphy** [iAmMe27/Tahrovin#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by iAmMe27** [comment]
This is not an issue with Tahrovin.

This is a known bug with the v3.0.1.6 release of Wabbajack. I'd recommend using v2.5.3.28 for now.

**Comment by BoobyMurphy** [comment]
Thank you, I actually added a file named profiles after the delete check and it worked. Lol
Love the work, and thanks again.
