### ISSUE TITLE
VRIK Mod Configuration Menu Doesn't Open - Crashes mod Config

### ISSUE THREAD

**Issue by TheHotHomeUser** [iAmMe27/Tahrovin#24]
**Describe the bug**

Opening the VRIK Mod Config menu shows a black empty menu. Once Ive backed out of VRIK's empty menu to the list of mods, I can no longer select any of the mods. I have to restart the game in order to be able to open other mods again.

**To Reproduce**

Following the install steps, I am on the part where we must set up the last couple of mod configs.

1. Open "VRIK" in the mod configuration menu

**Expected behavior**
VRIK menu opens

**Screenshots**
![20221220132830_1](https://user-images.githubusercontent.com/121126638/208742554-fa9f4faa-5484-4048-bd66-a536955d9b1a.jpg)

**Comment by iAmMe27** [comment]
You are on an old version of Tahrovin, please update and try this again.

**Comment by TheHotHomeUser** [comment]
I downloaded it directly from Wabbajack 2 days ago. Has it been updated since then?
