### ISSUE TITLE
Mod updated and breaks list

### ISSUE THREAD

**Issue by Toffeyman** [iAmMe27/Tahrovin#25]
Hi there, the mod below is no longer available and has a new version ending B not A, this has broken the list from working in Wabbajack.

MoreNastyCrittersSE_v12_8A

(https://www.loverslab.com/files/file/5464-more-nasty-critters-special-edition/)

**Comment by iAmMe27** [comment]
Thanks for this, I'll update the mod list shortly.

**Comment by Toffeyman** [comment]
Thanks, it looks like an incredible list with a lot of hard work and I can't wait to try it !

**Comment by iAmMe27** [comment]
Tahrovin has been updated and is now installable again.
