### ISSUE TITLE
Expression Morphs mod

### ISSUE THREAD

**Issue by sharkysi** [iAmMe27/Tahrovin#27]
Hi iAmMe27

The Expression Morphs mod is an esl so I have to manually rename the extension to esp for SkyrimVR to recognise its existence.

Love the mod list, great work :)

**Comment by iAmMe27** [comment]
Thanks for the reminder on this - it's on my to-do list but I keep forgetting to check my list!

I'll keep the issue open until I do it as a reminder :)

**Comment by sharkysi** [comment]
No problem :)

**Comment by iAmMe27** [comment]
Fixed
