### ISSUE TITLE
Sky Idles

### ISSUE THREAD

**Issue by sharkysi** [iAmMe27/Tahrovin#28]
Hi iAmMe27, apologies me again

Sky Idles is only usable for Player Characters in 3rd person mode, so no good for VR also it doesnt work on NPCs.  EVG Condition Idles might be a better option as it works on NPCs and you can switch off the player idles in the MCM

**Comment by iAmMe27** [comment]
Will remove.

**Comment by sharkysi** [comment]
EVG Condition Idles is a good replacer if you want to use that (Uses DAR)
