### ISSUE TITLE
Real VR Weathers and SkyVRraan

### ISSUE THREAD

**Issue by sharkysi** [iAmMe27/Tahrovin#29]
Last one honest :)

I noticed by chance that Real VR Weathers suggests to remove the SkyVRaan Weather plugin ( SkyVRaanWeatherPatcher.dll,  SkyVRaanWeatherPatcher.ini &  SkyVRaanWeatherPatcher.pdb).  I have hidden them in MO2, not noticed any issues/changes yet though

**Comment by iAmMe27** [comment]
SkyVRaan is a superior water mod for VR, very much so over anything else and they work together just fine.

**Comment by iAmMe27** [comment]
Oh I see what you mean - the weather patcher just adjusts water colour to allow for nicer water reflections. You can actually use the Synthesis patcher for it with other weather mods to get some nice water reflections.

**Comment by sharkysi** [comment]
Yeah SkyVRaan is superior to Water for ENB and RW2
