### ISSUE TITLE
CBBE not working correctly?

### ISSUE THREAD

**Issue by ej7819** [iAmMe27/Tahrovin#3]
Hi, I installed Tahrovin via the official wabbajack and tried following instructions to the best of my ability (I've previously used FUS and Narsil before, as well as added mods from Nexus on my own.)

But something seems to have not worked properly in my install?  The bodies don't look right, and I don't see any changes when I adjust the CBBE sliders in Racemenu.  Male NPCs have their underwear on, and no schlongs.  When doing the "lowering herself onto a potion bottle" animation, the animation simply plays the sitting down part over and over.

I've only ever used BHUNP, not CBBE before - are the women supposed to look so muscular, with heavily defined abs and stuff?

Did I do something incorrectly?  How can I fix things?

Thanks

**Comment by iAmMe27** [comment]
Did you install from Wabbajack recently?

I've never seen an issue with NPC bodies before except for when I broke animations but that leads to obvious A-posing in-game.

RaceMenu VR is a little buggy still, you often need to adjust the CBBE morphs and then adjust the weight slider in the "Body" tab back and forth to force the morphs to update.

The muscular bodies are deliberate yes, the maps are provided by the Leyenda Skin - there's an additions channel on the Jolly Co-operators Discord server if you want to discuss changes.

**Comment by ej7819** [comment]
Thanks for the reply.  I installed from Wabbajack a couple of days ago.

Is SOS supposed to work out of the box? Or do I need to do something for the schlongs to appear?

Can I just install another skin on top? For example, I usually use Bijin skin.

**Comment by iAmMe27** [comment]
SOS does work out of the box, yes. In RaceMenu, males have underwear by default and I think that's something forced by RaceMenu for some odd reason. I've yet to work out why it does it.

Leyenda has different muscle levels, try reinstalling that in place. The Discord server is the best place for changes though as it then becomes and issue outside the scope of the official list. 

Discord server is here: https://discord.gg/jolly-coop

**Comment by ej7819** [comment]
In my case, males still have underwear during gameplay, like during sex and stuff.  At least in Lorkhan, I havent exited Lorkhan yet.

I'll try reinstalling Leyenda, thanks.
