### ISSUE TITLE
Tahrovin installation error

### ISSUE THREAD

**Issue by CousinRed** [iAmMe27/Tahrovin#30]
Hi, I'm getting an error while installing Tahrovin...

Log file attached

Thanks!
[Wabbajack.current.log](https://github.com/iAmMe27/Tahrovin/files/10846141/Wabbajack.current.log)

**Comment by iAmMe27** [comment]
Download the Skyrim VR ENB files from the ENB website and drop into your WJ downloads folder.

**Comment by CousinRed** [comment]
That worked... thanks and thanks for the incredible modlist!

I'm so excited!
