### ISSUE TITLE
VR Body Gone After Running Nemesis

### ISSUE THREAD

**Issue by Flowrif** [iAmMe27/Tahrovin#31]
**Describe the bug**
After running Nemesis Behavior Update Engine, I cannot see my body in-game anymore. The reason for running Nemesis is because I added a mod that requires this step.

**To Reproduce**
1. Open Tahrovin MO2 '
2. Click on 'Open Nemesis from MO2 drop down menu.'
3. Click 'update engine' and let finish
4. Click 'Launch Nemesis' button. All the animation are scanned successfully.
5. Open the game and when it loads, my VR body is completely gone.  Issue is persistent with new game as well.

**Expected behavior**
I expect to see my VR body. Please let me know if I am doing something wrong or if I am missing a step.

**Screenshots**

**Additional context**
Please let me know if I am doing something wrong or if I am missing a step. Maximum Carnage is the mod that requires me to run Nemesis. 
![Nemesis](https://user-images.githubusercontent.com/100743148/225422935-9ad94ad9-90fa-4646-a2da-77179df9d207.png)
![Nemesis2](https://user-images.githubusercontent.com/100743148/225422937-079f88f7-009d-47d8-9135-d4df570978c9.png)

**Comment by iAmMe27** [comment]
This would be classified as a modlist modification and GitHub issues are for modlist bugs.

I recommend checking in with people in the #tahrovin-modifications channel on Discord for some help with this one.

**Comment by Flowrif** [comment]
Ok will do. TY!

**Comment by Flowrif** [comment]
darn, the Discord invite is not working

**Comment by iAmMe27** [comment]
https://discord.gg/jolly-coop

**Comment by Flowrif** [comment]
showing "unable to accept invite."

**Comment by iAmMe27** [comment]
No idea, works fine on my end

**Comment by Flowrif** [comment]
Bruizerhands#5428
