### ISSUE TITLE
Black Box

### ISSUE THREAD

**Issue by Rufim** [iAmMe27/Tahrovin#32]
**Describe the bug**
When I activate ENB VrVision in center of screen floating black box with something on it sometimes blocking vision.

**To Reproduce**
Install game though gude.
Enable ENB VrVision. Sync.
Start new game.

**Expected behavior**
No black window.

**Comment by iAmMe27** [comment]
Open the DLSS menu by pressing END on your keyboard and then toggling TAA OFF and then back to ON again

![image](https://user-images.githubusercontent.com/98499526/228615616-efad8d94-40e9-4d39-aa36-567620b4d716.png)

**Comment by Rufim** [comment]
Thank you!
