### ISSUE TITLE
FSR2.2.zip not downloading

### ISSUE THREAD

**Issue by Starteller** [iAmMe27/Tahrovin#33]
FSR2.2.zip not downloading
even if I manually download and put it in the download folder it is not working

**Comment by RagingOvac** [comment]
I have the same problem, i think it's a problem with the hash. It said it could not download, so i manually did it but when i copied the FSR2.2.zip file in the downloads file, it was already there so i replaced it thinking it would work. It didn't, here's the log. Hopes it helps.
[Wabbajack.current.log](https://github.com/iAmMe27/Tahrovin/files/11241888/Wabbajack.current.log)

**Comment by iAmMe27** [comment]
Download this version and drop it into your WJ downloads folder: https://github.com/PureDark/FidelityFX-FSR2/releases/download/2.2-unofficial/FSR2.2.zip

**Comment by RagingOvac** [comment]
That worked, thank you for the quick help and the modlist.
