### ISSUE TITLE
xlodgen.94.7z can't be downloaded

### ISSUE THREAD

**Issue by SoulsDew** [iAmMe27/Tahrovin#34]
xlodgen.94.7z can't be downloaded by wabbajack you got a link for it/ fix it in you grab code thanks

**Comment by iAmMe27** [comment]
Known problem, it was removed from the WJ CDN and I haven't had a chance to update yet. 

Can download from here: https://cdn.discordapp.com/attachments/966098060008652901/1102983512635740160/xLODGen.94.7z
