### ISSUE TITLE
NPC bodies do not match up when clothed/nude

### ISSUE THREAD

**Issue by AriochsFall** [iAmMe27/Tahrovin#35]
When the clothes are taken of an NPC (mainly followers from what I've seen) the AutoBody morph does not match the same one when clothed EX; Lydia having her morph excessively large when nude but not having the same size body when she has armor on.

**Comment by iAmMe27** [comment]
Sounds to me like your install is messed up and the bodyslide output hasn’t been installed properly.

> Message ID: ***@***.***>

Try rerunning WJ.

**Comment by AriochsFall** [comment]
Ok, I'll let you know the result, thanks.

**Comment by AriochsFall** [comment]
It's still present after reinitializing the WJ

**Comment by iAmMe27** [comment]
I wasn't able to replicate this at all testing for this issue yesterday.

**Comment by AriochsFall** [comment]
Here's two screenshots, they're in god awful quality with artifacting, but they should be enough.
![ScreenShot1](https://github.com/iAmMe27/Tahrovin/assets/133561819/0ff440a3-c356-4318-b8b2-8200254a3646)
![ScreenShot0](https://github.com/iAmMe27/Tahrovin/assets/133561819/3f495c01-0f99-4841-88a7-4db95d7a12d2)

**Comment by AriochsFall** [comment]
I have made an interesting discovery, apparently it seems to only happen with Lydia, I tried on other followers and it seems to be just Lydia.
