### ISSUE TITLE
Character not animating when "engaging" with wolves

### ISSUE THREAD

**Issue by pine-bark** [iAmMe27/Tahrovin#4]
When attacked by wolves a scene correctly triggers but the female player character animations do not play. Attempted multiple fresh saves and reinstalls but unfortunately I cant seem to find a solution.  Advancing to the next animation does not help nor does resetting positioning. 

Should be easy to reproduce, just wander the hills outside Whiterun till you are mobbed by the critter in question. 

As far as I can tell, the player character is correctly animating when engaging with any other creature type that I've tested.

**Comment by iAmMe27** [comment]
This is now fixed, was an issue with FNIS and Nemesis interaction with the FNIS specific ESP. I've tested the fix myself and it has worked reliably when engaging these animations a few times.

Fix will be released in the next update to Tahrovin.
