### ISSUE TITLE
Armor gets One-shotted off enemys and myself

### ISSUE THREAD

**Issue by Ex1tu5** [iAmMe27/Tahrovin#6]
Is there any Setting I can change in that regard or turn off a mod?
Every Time i get hit my Armor is destroyed, wich is pretty annoying.

**Comment by iAmMe27** [comment]
This is a setting in Yamete.

If you have questions about Tahrovin, please join the Jolly Co-Operators Discord server where the official support for Tahrovin is. https://discord.gg/jolly-coop

GitHub issues are for actual issues/bugs with the modlist.
