### ISSUE TITLE
How can I add new mods (that may require Nemesis/Bodyslider etc)?

### ISSUE THREAD

**Issue by SiIith** [iAmMe27/Tahrovin#7]
Hello not sure if this is the right place to ask questions but will greatly appreciate if you could help.

I've installed the modlist using Wabbajack and the game ran without pain, but I was a bit confused when I tried to port over some of my SE mods here. I used the MO2 packed in the installation folder to install the mods which worked fine, but some outfit mods require Bodyslider and some animation mods require Nemesis/FNIS, which I didn't find a way. Can you help explain briefly how do I do this?

Thanks in advance :)

**Comment by iAmMe27** [comment]
Best place to ask is in the additions channel for Tahrovin in the Jolly Co-Operators Discord server: https://discord.gg/jolly-coop

GitHub issues is more for issues with the unmodified list.
