### ISSUE TITLE
Unable to finish installing on Wabbajack.

### ISSUE THREAD

**Issue by Ederax** [iAmMe27/Tahrovin#9]
I know you already replied to a similar question, but it was a month ago. I am stuck on this blank screen where they are asking me to login into Vector Plexus (during the installing on Wabbajack). I know the problem is coming from Vector Plexus but is there no way around it? Can I not get the mod list elsewhere? Or am I screwed?

**Comment by iAmMe27** [comment]
Please join the support Discord server.

There is an alternative link provided by the mod author before the main VectorPlexus site went down.
